src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column]
    private ?int $wallet = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Difficulty $Difficulty = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getWallet(): ?int
    {
        return $this->wallet;
    }

    public function setWallet(int $wallet): self
    {
        $this->wallet = $wallet;

        return $this;
    }

    public function getDifficulty(): ?Difficulty
    {
        return $this->Difficulty;
    }

    public function setDifficulty(?Difficulty $Difficulty): self
    {
        $this->Difficulty = $Difficulty;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Matche;
use App\Repository\MatcheRepository;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(MatcheRepository $matcheRepository): Response
    {
        $matchesWithoutScore = $matcheRepository->findMatchesWithoutScore();

        return $this->render('home/index.html.twig', [
            'matches' => $matchesWithoutScore,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Accueil
{% endblock %}

{% block body %}

	<div class="flex flex-col items-center justify-center pt-12">
		<h1 class="text-4xl underline mb-4">Matches</h1>
		{% for matche in matches %}
			<div class="w-2/4 flex flex-col items-center gap-10 border py-10 px-20 mb-10">
				<div class="flex gap-32 items-center">
					<h2 class="text-2xl">
						{{ matche.Player1.firstName }}
						-
						{{ matche.Player1.lastName }}
					</h2>
					<p>VS</p>
					<h2 class="text-2xl">
						{{ matche.Player2.firstName }}
						-
						{{ matche.Player2.lastName }}
					</h2>
				</div>
				<div class="flex gap-3">
					<a href="{{ path('app_matche_show', {'id': matche.id}) }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-5 rounded">
						Détail
					</a>
					<a href="{{ path('app_matche_bet', {'id': matche.id}) }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-5 rounded">
						Parier
					</a>
				</div>
			</div>
		{% endfor %}
	</div>

{% endblock %}